### ISSUE TITLE
FOSS?

### ISSUE THREAD

**Issue by IdleCoyote** [zig13/scenzig#1]
Hi.

I read about scenzig in the post at intfiction.org: https://www.intfiction.org/forum/viewtopic.php?f=33&t=25452

I was interested in scenzig because the subject said it was "FOSS" but there seems to be a non-FOSS license in play: CC BY-NC-SA, so I feel confused.

Ignoring, for a moment, that Creative Commons recommends against using the licenses for software (see https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), anything with a "non-commercial" clause is neither free software nor open source:

- The Free Software Foundation has https://www.gnu.org/philosophy/free-sw.html which holds that "'Free software' does not mean 'noncommercial'. A free program must be available for commercial use, commercial development, and commercial distribution."

- Meanwhile, the Open Source Initiative has https://opensource.org/osd-annotated which holds that an open source license: "6. No Discrimination Against Fields of Endeavor. The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research. Rationale: The major intention of this clause is to prohibit license traps that prevent open source from being used commercially. We want commercial users to join our community, not feel excluded from it."

- They also have https://opensource.org/faq#commercial has that "Q: Can Open Source software be used for commercial purposes? A: Absolutely. All Open Source software can be used for commercial purpose; the Open Source Definition guarantees this. You can even sell Open Source software."

Would you change the license to something that does not have a non-commercial clause -- so that it really can be FOSS? And second, using a real software license? There are quite a few of them on https://www.gnu.org/licenses/license-list.html and on https://opensource.org/licenses to pick from.

**Comment by zig13** [comment]
Thank you for bringing this to my attention.
Primarily I was just trying to find a way to fit a summary in the subject field. Simplistically Scenzig's code is publicly, freely available so I thought it was appropriate. It seems FOSS is more loaded than I understood and I am sorry to have deceived you.

I think I did look into other licences but was worried someone would be able to commercialize it. I now understand that a 'Copy-Left' license would scupper such attempts.

I will change the licence later today (when I am back at a computer) to GNU General Public License version 3 unless you have a better suggestion.

Thanks!
